### ISSUE TITLE
Provide program guide additionally to live show information

### ISSUE THREAD

**Issue by ialokim** [mediathekview/zapp-backend#17]
I've searched through the issues here and over at the Android app repo and just found https://github.com/mediathekview/zapp/issues/22 going into the same direction. I guess this repo would be the right one to have this implemented.

I think it would be nice to show the upcoming programs on the same day (or at least within the next few hours) within zapp, similar as to how the current (live) program is displayed. My concrete use-case is that I would like to know when the news are scheduled on this day without opening and looking at several official websites.

I've already looked into the information available for the different channels, here's my summary:
- the currently used [ARD API](https://programm.ard.de/TV/Export/Now) returns information for the upcoming three programs. For more information, I think it might not be that difficult to scrape their official [program website](https://programm.ard.de/TV/Programm/Sender). Do you know a better source to get this additional information from (some sort of API, perhaps used by their apps)?
- the currently used ZDF API seems to return arbitrary many program informations using the `limit=x` URL parameter
- the DW API per default returns information for 24 hours
- the Parliament XML seems to contain information for the next couple of days

What are your thoughts on this? When I find some time and if you'd be okay with it, I would like to contribute to this being implemented.

**Comment by cemrich** [comment]
Thank you very much for this detailed feedback!

I am afraid, this feature is currently out of scope for Zapp. Due to the pandemic and non existent free time I have to heavily prioritize which features I am able to develop - and more important - to maintain. This is especially a problem for ever changing and not documented third party apis.

An open source program schedule api should definitely exist (and I honestly wonder, why it doesn't) but currently it will not be part of Zapp :(

**Comment by ialokim** [comment]
Okay, that's a pity, but I totally understand that! Let's see if me or someone else eventually finds the time to write (and maintain) such an API that could then be perhaps added to Zapp - I'd highly appreciate it :)
